### PR TITLE
Add types and update to 1.3.3

### PR DESCRIPTION
**Pull request by leonardobazico**

### CODE REVIEW

**Comment by idanwe** [comment]
@leonardobazico thank you very much!
I think it is needed to update [accounts-base-client-side](https://github.com/idanwe/accounts-base-client-side) too, Would you be able todo it?

**Comment by leonardobazico** [comment]
Sure! It's my next step

On 13 Jan 2017, at 07:08, Idan Wender <notifications@github.com> wrote:

@leonardobazico thank you very much!
I think it is needed to update accounts-base-client-side too, Would you be able todo it?

**Comment by idanwe** [comment]
@leonardobazico at the next PR don't update the version. It's better for me todo it with the tags

**Comment by idanwe** [comment]
@phamtrong204 I need your permission to publish the package to npm under the name `accounts-password-client-side` and `accounts-base-client-side` can you at me as collaborator?

**Comment by leonardobazico** [comment]
@idanwe, I want do a similar repo for accounts-facebook, accounts-google, etc.

How you know what packages is necessary to concat in *.bundle.js?

in accounts-base you do:
```
cat "$PACKAGES_PATH/callback-hook.js" >> $OUTPUT_PATH/$NAME.bundle.js
cat "$PACKAGES_PATH/localstorage.js" >> $OUTPUT_PATH/$NAME.bundle.js
cat "$PACKAGES_PATH/accounts-base.js" >> $OUTPUT_PATH/$NAME.bundle.js
```

and in accounts-password:
```
cat "$PACKAGES_PATH/sha.js" >> $OUTPUT_PATH/$NAME.bundle.js
cat "$PACKAGES_PATH/srp.js" >> $OUTPUT_PATH/$NAME.bundle.js
```

Basic you see what the package import and what is not included in global-imports?

**Comment by phamtrong204** [comment]
@idanwe I have add you to collaborators list of `accounts-password-client-side` and `accounts-base-client-side`

I have publish  `accounts-password-client-side` with version 1.3.3 and 1.3.4. v1.3.4 is my mistake, there is no any change in this version, but i can unpublish this.
I try:
```
npm unpublish accounts-password-client-side@1.3.4 -f
```
and get error:
```
npm ERR! unpublish Failed to update data
...
npm ERR! "accounts-password-client-side status = 403" : accounts-password-client-side
```

Unpublish it if you can, thankyou very much.

**Comment by idanwe** [comment]
@phamtrong204 @leonardobazico I couldn't publish v1.3.3 / v.1.3.4 so I publish the new version as 1.3.5

**Comment by idanwe** [comment]
@leonardobazico Regard releasing accounts-facebook, etc..

I described it at [this comment at #2](https://github.com/idanwe/accounts-password-client-side/issues/2#issuecomment-162036663)

And there was several discussions #2, #6, [idanwe/meteorc-client-side#23](https://github.com/idanwe/meteor-client-side/issues/23), 

There was a try to create [accounts-facebook](https://github.com/mixersoft/accounts-facebook-client-side), But I don't now what is the status of the repo.

**Pull request merged**
